class ProductModel {
  final String name;
  final String image;
  final double price;
  bool isFavourite;
  bool isAddCard;

  ProductModel({
    required this.name,
    required this.image,
    required this.price,
    required this.isFavourite,
    required this.isAddCard,
  });
}

List<ProductModel> productsList = List.generate(100, (index) {
  List<String> clothingNames = [
    "Classic White T-Shirt",
    "Slim Fit Blue Jeans",
    "Casual Black Hoodie",
    "Red Checkered Shirt",
    "Denim Jacket",
    "Cotton Polo Shirt",
    "Graphic Print T-Shirt",
    "Beige Chinos",
    "Leather Jacket",
    "Formal White Shirt",
    "Oversized Hoodie",
    "Sports Joggers",
    "Summer Shorts",
    "Woolen Sweater",
    "Crop Top",
    "Maxi Dress",
    "Mini Skirt",
    "High-Waist Trousers",
    "Puffer Jacket",
    "Bomber Jacket",
    "V-Neck Sweater",
    "Sleeveless Tank Top",
    "Linen Shirt",
    "Cargo Pants",
    "Cardigan Sweater",
    "Plaid Shirt",
    "Ripped Skinny Jeans",
    "Long Coat",
    "Athletic Shorts",
    "Basic Black T-Shirt",
    "Round Neck T-Shirt",
    "Yoga Leggings",
    "Running Jacket",
    "Sports Bra",
    "Hooded Sweatshirt",
    "Knitted Pullover",
    "Fleece Jacket",
    "Silk Blouse",
    "Formal Blazer",
    "Pencil Skirt",
    "Denim Overalls",
    "Raincoat",
    "Windbreaker Jacket",
    "Henley Shirt",
    "Turtleneck Sweater",
    "Cropped Hoodie",
    "Dungarees",
    "Track Pants",
    "V-Neck T-Shirt",
    "Off-Shoulder Top",
    "Pleated Skirt",
    "Harem Pants",
    "Boyfriend Jeans",
    "Kimono Jacket",
    "Striped Polo Shirt",
    "Sequin Dress",
    "Overshirt Jacket",
    "Culottes Pants",
    "Rugby Shirt",
    "Biker Leather Jacket",
    "Peacoat Jacket",
    "Sweat Shorts",
    "Lace Top",
    "Denim Shirt",
    "Chiffon Dress",
    "Summer Tank Dress",
    "Lounge Pants",
    "Longline T-Shirt",
    "Graphic Hoodie",
    "Embroidered Kurti",
    "Kurta Pajama",
    "Sherwani Suit",
    "Ethnic Anarkali Dress",
    "Evening Gown",
    "Party Blazer",
    "Double-Breasted Coat",
    "Safari Jacket",
    "Track Jacket",
    "Quilted Jacket",
    "Leather Vest",
    "Denim Vest",
    "Printed Saree",
    "Silk Saree",
    "Cotton Kurta",
    "Formal Suit",
    "Velvet Blazer",
    "Winter Parka",
    "Long Wool Coat",
    "Sweater Vest",
    "Cape Jacket",
    "Maxi Skirt",
    "Wrap Dress",
    "Knit Dress",
    "Crop Jacket",
    "Sports Tracksuit",
    "Oversized T-Shirt",
    "Tie-Dye Hoodie",
    "Polo Dress",
    "Faux Fur Jacket",
    "Hooded Parka",
  ];
  List<String> images = [
    "assets/images/43.png",
    "assets/images/44.png",
    "assets/images/54.png",
    "assets/images/433.png",
    "assets/images/544.png",
    "assets/images/product 1.png",
  ];

  return ProductModel(
    name:
        clothingNames[index %
            clothingNames.length], // cycle through 100 real clothing names
    image: images[index % images.length], // cycle through images
    price: 10.0 + (index % 50), // prices from 10 → 59
    isFavourite: false,
    isAddCard: false,
  );
});
